services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.notajot.duckdns.org`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsEncrypt
    user: '0'
    volumes:
      - './data:/var/lib/grafana'
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "VmadK3fWIgIxrH6ZBnH6SSfeskFAXOf8X1vLGyMV"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "9VnijUIUVwaYlxNazsxcd20pw072OZDKAyLGiBloO5Te56pYwMTCD1fNGLDsQ8WThY9rqCBZ5SzFE2pIOxL4OyyaatyCeHXXPzYgd22MHOnIY67mJb0DCADhrn9ffz4q"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.notajot.duckdns.org/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.notajot.duckdns.org/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.notajot.duckdns.org/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.notajot.duckdns.org/application/o/grafana/end-session/"
      # Optionally enable auto-login (bypasses Grafana login screen)
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      # Optionally map user groups to Grafana roles
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
      GF_SERVER_ROOT_URL: "https://grafana.notajot.duckdns.org"
networks:
  frontend:
    external: true