http:
  routers:
    immich:
      entryPoints:
        - "websecure"
      rule: "Host(`immich.notajot.duckdns.org`)"
      middlewares:
        - default-headers
        #- addprefix-immich
      tls:
        certResolver: http
      service: immich
    distribution:
      entryPoints:
        - "websecure"
      rule: "Host(`distribution.notajot.duckdns.org`)"
      middlewares:
        - default-headers
      tls:
        certResolver: http
      service: distribution

  services:
    immich:
      loadBalancer:
        servers:
          - url: "http://192.168.16.50:30041"
        passHostHeader: true
    distribution:
      loadBalancer:
        servers:
          - url: "http://192.168.16.50:30095"
        passHostHeader: true

  middlewares:
    addprefix-immich:
      addPrefix:
        prefix: "/photos"

    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/24"
        - "192.168.0.0/16"
        - "172.0.0.0/8"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
